### ISSUE TITLE
Question regarding LOMO

### ISSUE THREAD

**Issue by Neukiru** [BorealisAI/flora-opt#2]
Are LOMO style updates already integrated into Flora optimizer?

**Comment by yongchanghao** [comment]
Yes it is automatically enabled when using Flora for PyTorch. See https://github.com/BorealisAI/flora-opt/blob/5d7f43440071ef66a67d81148b4d1f409259c312/flora_opt/optimizers/torch/flora.py#L88 and https://github.com/BorealisAI/flora-opt/blob/5d7f43440071ef66a67d81148b4d1f409259c312/flora_opt/optimizers/torch/flora.py#L260

**Comment by Neukiru** [comment]
> Yes it is automatically enabled when using Flora for PyTorch. See
> 
> https://github.com/BorealisAI/flora-opt/blob/5d7f43440071ef66a67d81148b4d1f409259c312/flora_opt/optimizers/torch/flora.py#L88
> 
> and
> https://github.com/BorealisAI/flora-opt/blob/5d7f43440071ef66a67d81148b4d1f409259c312/flora_opt/optimizers/torch/flora.py#L260



> Yes it is automatically enabled when using Flora for PyTorch. See
> 
> https://github.com/BorealisAI/flora-opt/blob/5d7f43440071ef66a67d81148b4d1f409259c312/flora_opt/optimizers/torch/flora.py#L88
> 
> and
> https://github.com/BorealisAI/flora-opt/blob/5d7f43440071ef66a67d81148b4d1f409259c312/flora_opt/optimizers/torch/flora.py#L260

Thank you <3

**Comment by Neukiru** [comment]
closing the issue
