### ISSUE TITLE
Clean install of `flora-opt[torch]` fails import

### ISSUE THREAD

**Issue by atong01** [BorealisAI/flora-opt#3]
```
Python 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from flora_opt import Flora
>>> Flora
>>> print(Flora)
None
```

**Comment by atong01** [comment]
This looks like a problem with the pypi package version. Seems to work when installed from source. The pipit package looks like it's missing many files to me.

**Comment by yongchanghao** [comment]
Thanks for reporting this! I have fixed this issue in commit https://github.com/BorealisAI/flora-opt/commit/c50ee5224df2c9e2f2d75c91a86f3ae2b9d641d6. The PyPI package is also updated to this commit. Please try updating `flora-opt` from PyPI and see whether it fixes your issue.
